language: node_js
node_js:
  - lts/carbon
env:
  global:
    - NPM_CONFIG_LOGLEVEL=warn
before_install:
  - nvm install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
install:
  - bundle install --without production --path=${BUNDLE_PATH:-vendor/bundle}  # Install ruby gems, excluding production only gems such as unicorn (already present by default in Travis)
  - npm install
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
# Setup the database
before_script: bundle exec rake db:create db:migrate
script:
    - npm run install:all
    - npm run lint:all
    - npm run test:all
    - npm run build:all
    - bundle exec rspec
# Pipe the coverage data to Code Climate
after_script:
  - ./cc-test-reporter format-coverage -t simplecov -o client/coverage/coverage-final.json client/coverage/lcov.info # client coverage
  - ./cc-test-reporter format-coverage -t lcov -o server/coverage/coverage-final.json server/coverage/lcov.info  # Server coverage
  - ./cc-test-reporter sum-coverage */coverage/coverage-final.json -p 2                  # Sum both coverage parts into coverage/codeclimate.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json
